### ISSUE TITLE
List features that are excluded from Requirement 1.3

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-vnext-reqs#11]
See:

https://github.com/w3c/imsc/issues/279
https://github.com/w3c/imsc/issues/278
https://github.com/w3c/imsc/issues/277
https://github.com/w3c/imsc/issues/276
https://github.com/w3c/imsc/issues/275
https://github.com/w3c/imsc/issues/273

**Comment by palemieux** [comment]
Blocked by https://lists.w3.org/Archives/Public/public-tt/2017Nov/0107.html

**Comment by nigelmegitt** [comment]
Note that the block was removed some time ago, via an agreement to remove some TTML2 features directly equivalent to IMSC 1.0.1 extensions from TTML2.
