### ISSUE TITLE
is tts:textShadow required?

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-vnext-reqs#13]
See https://github.com/w3c/imsc-vnext-reqs/pull/9#pullrequestreview-75334210

**Comment by nigelmegitt** [comment]
Thanks, I was just about to open the very same issue! The question in summary is: if `tts:textOutline` were supported, would `tts:textShadow` support still be required to support some regulatory requirement? 

Mentioning @mikedo who was asked about this in the (now merged) pull request, to alert him to the fact that the discussion has moved.

**Comment by nigelmegitt** [comment]
See https://github.com/w3c/imsc-vnext-reqs/pull/9#issuecomment-345751081

**Comment by palemieux** [comment]
Propose keeping `tts:textShadow` given its potential mapping to 708 and direct mapping to CSS.

**Comment by nigelmegitt** [comment]
Then how will you resolve both textOutline and textShadow being present at the same time?

**Comment by palemieux** [comment]
> Then how will you resolve both textOutline and textShadow being present at the same time?

They are different effects: the first grows the outline of each glyph, while the second creates multiple copies of the glyph.

**Comment by palemieux** [comment]
P.S.: I do not know why anyone would use both simultaneously, but their effects can be cumulated, e.g. first draw outline and then draw shadow.

**Comment by mikedo** [comment]
textShadow meets the one CTA 708 property (Edge Type) that can't be done today in TTML.  From a  708 perspective we don't need both, certainly not concurrently. So, if we are going to remove/deprecate one, it should be textOutline.

**Comment by palemieux** [comment]
>  So, if we are going to remove/deprecate one, it should be textOutline.

`textOutline` is the effect used for home video content, e.g. on Blu Ray.

... so it sounds like we need both until further notice.
