### ISSUE TITLE
Specify deprecation model

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc-vnext-reqs#14]
Netflix has requested that IMSC 1.1 should indicate that when TTML2 features are used in the same document at the same time as their non-TTML2 equivalent and deprecated features [from IMSC 1.0.1] the TTML2 features prevail.

The motivation is "this ensures that future versions of IMSC can effectively remove the features marked as deprecated".

**Comment by palemieux** [comment]
See https://lists.w3.org/Archives/Public/public-tt/2017Nov/0107.html

**Comment by palemieux** [comment]
The request above is not easily achievable in many cases, e.g. if `condition` replaces `itts:forcedDisplay`.

**Comment by nigelmegitt** [comment]
Thanks for the reference @palemieux

**Comment by nigelmegitt** [comment]
> The request above is not easily achievable in many cases, e.g. if `condition` replaces `itts:forcedDisplay`.

You mean that it is complex to do in the spec and might require additional authorial support?

An authorial mechanism would be a construct or pattern that checks for feature support for `condition` and if present, uses it to exclude the `itts:forcedDisplay` style and instead to make a further test of the forced parameter, and then use the outcome of that test to set `tts:visibility`.

**Comment by palemieux** [comment]
It is too complex for processors to detect the presence of both, and apply precedence rules.

**Comment by nigelmegitt** [comment]
@palemieux that would be a comment worth making on w3c/imsc#279

**Comment by skynavga** [comment]
@palemieux your statement seems wholly subjective and without factual support

**Comment by palemieux** [comment]
@skynavga Per https://github.com/w3c/ttml2/issues/482#issuecomment-342324353, `itts:forcedDisplay` would be deprecated in favor of syntax along the lines of the following:

```xml
<style xml:id="forcedStyleFalse" condition="parameter(forced)==false" tts:visibility="false"/>
<style xml:id="forcedStyleTrue" condition="parameter(forced)==true" tts:visibility="true"/>
<style xml:id="forcedStyle" style="forcedStyleFalse,forcedStyleTrue"/>
...

<p style="forcedStyle">This text is only visible if forced==true</p>
```

so how would a processor enforce precedence rules when encountering the following:

```
<p itts:forcedDisplay="true" style="forcedStyle">This text is only visible if forced==true</p>
```

**Comment by nigelmegitt** [comment]
The deprecation model needs to define what deprecation should mean in this context. I think from our meetings that we are all agreed that deprecated features are permitted but are expected to be prohibited by future versions of the specification.
