### ISSUE TITLE
Consider adding support for "before" and "after" annotation position

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-vnext-reqs#23]
Only `"outside"` is currently required for `#rubyPosition` and the position component of `#textEmphasis`.

Since `"outside"` is optimized for two-line blocks, it is not clear that this is sufficient to support 2+ lines (and even 1 line).

Recommend consider supporting `"before"` and `"after"` as well.

**Comment by nigelmegitt** [comment]
Will this issue still be valid after w3c/ttml2#798 has been merged?

**Comment by palemieux** [comment]
@nigelmegitt I think so, since 'outside` is only intended to be used with 1- or 2-line blocks.
