### ISSUE TITLE
Since some style attributes are permitted in Image profile, permit `#initial`

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc-vnext-reqs#36]
There are style attributes that are permitted in Image Profile, such as `tts:backgroundColor`, `tts:display`, `tts:luminanceGain` etc. so it makes sense to permit `#initial` in Image Profile for ease of styling, and symmetry with Text Profile.

**Comment by palemieux** [comment]
I am not aware of Image profile use cases that cannot be fulfilled without `initial`, and not aware of Image profile users that have requested that feature.

**Comment by nigelmegitt** [comment]
OK but it's weirdly inconsistent. If we think `initial` is useful for Text Profile, why would it not be useful for Image Profile?
