### ISSUE TITLE
I would like to see a requirement to identify an IMSCvNext document as such

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-vnext-reqs#5]
For example, using some combination of ttp:profile and/or ttp:version.

From @skynavga

**Comment by nigelmegitt** [comment]
Can this be done in a way that does not make otherwise conformant IMSC 1 or EBU-TT-D documents non-conformant if they do not have the content profile identifier in the document?

**Comment by palemieux** [comment]
As specified in https://github.com/w3c/imsc/pull/267, it is possible unless compatibility with EBU-TT-D, IMSC1 or SDP-US is desired.
