### ISSUE TITLE
Update per Netflix input document

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-vnext-reqs#8]
See https://lists.w3.org/Archives/Public/public-tt/2017Nov/0007.html

**Comment by nigelmegitt** [comment]
I'm not clear exactly what changes are being requested or proposed in this issue: the Netflix document is not a set of changes per se.

**Comment by palemieux** [comment]
The Netflix document specifies that only some variations of some features are used, e.g. only `tts:rubyAlign="auto"` is used
